layout_spectrum: 0.6696647983790366
typography_spectrum: 0.9058541823971538
color:
  brandStrength: 0.7023058782709707
  lightness: 1
  saturation: 0.9572629463785134
  rhythmicContrast: 0.17728347235921735
  brandColors:
    - '#000000'
    - '#404040'
    - '#808080'
    - '#BFBFBF'
    - '#FFFFFF'
github: true
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/0a13537f-4b5e-4468-9791-0e52b5b0400b.jpg
name: AlienOne Security
url: 'http://www.alienonesecurity.com'
favicon: null
title: AlienOne Security
content: []
description: It is about the human not the machine...
